require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rake
  - rubocop-rspec

AllCops:
  NewCops: enable
  Exclude:
    - 'bin/{bundle,rackup,rake,rspec,rubocop}'
    - 'builds/**/*'
    - 'vendor/**/*'

Lint/MissingSuper:
  Exclude:
    - 'app/services/**/*'

Metrics/BlockLength:
  Enabled: false
Metrics/MethodLength:
  Enabled: false

Style/Documentation:
  Enabled: false
Style/DocumentationMethod:
  Enabled: false

Rails/FilePath:
  EnforcedStyle: arguments

RSpec/MultipleExpectations:
  Enabled: false
RSpec/NamedSubject:
  Enabled: false
RSpec/NestedGroups:
  Enabled: false
RSpec/MultipleMemoizedHelpers:
  Enabled: false
RSpec/AnyInstance:
  Enabled: false
RSpec/MessageSpies:
  EnforcedStyle: 'receive'
